# This file was automatically generated by passthru.fetch-deps.
# Please don't edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Argu";
    version = "6.1.1";
    sha256 = "1v996g0760qhiys2ahdpnvkldaxr2jn5f1falf789glnk4a6f3xl";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "7.0.0";
    sha256 = "1pgk3qk9p1s53wvja17744x4bf7zs3a3wf0dmxi66w1w06z7i85x";
  })
  (fetchNuGet {
    pname = "HtmlAgilityPack";
    version = "1.11.43";
    sha256 = "08xh6fm5l9f8lhhkk0h9vrp8qa60qmiq8k6wyip8lqn810jld50m";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.0";
    sha256 = "1hjgmz47v5229cbzd2pwz2h0dkq78lb2wp9grx8qr72pb5i0dk7v";
  })
  (fetchNuGet {
    pname = "System.IO.Abstractions";
    version = "17.1.1";
    sha256 = "1pkqigqa0f62ma7cxhz5qiwfb7h6dmiszvzl3gr3pczc7ff4v3fi";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    sha256 = "1q8ljvqhasyynp94a1d7jknk946m20lkwy2c3wa8zw2pc517fbj6";
  })
]
